name: SneakyOnePlugin
version: 1.0
main: mc.sneakyone.yt.com.sneakyoneplugin.SneakyOnePlugin
api-version: 1.16
authors: [ SneakyOne ]
description: Плагин, рандомизирующий блоки вокруг вас
commands:
  startfill:
    description: Starts plugin
    usage: /startfill